### PR TITLE
reduced border radius for a dress in the show page

### PR DESCRIPTION
**Pull request by angrysun**

### CODE REVIEW

**Comment by CamillieFu** [comment]
Can we see what Keiran and Gary think first? It looks fine either way, but keeping the photos consistent across pages might seem a little bit like a cleaner design.

**Comment by angrysun** [comment]
Sure, let's wait and see what they think

**Comment by Gazwai** [comment]
My 2 cents is having consistency throughout the images would be better, but I don't mind since its not that big of a change

**Comment by KeiranBrown1301** [comment]
I think it would be fine since its a pretty small change.

**Comment by KeiranBrown1301** [comment]
Sorry for not commenting earlier too

**Pull request closed without merging**
